### ISSUE TITLE
Recording data in duplicates

### ISSUE THREAD

**Issue by chriskurze** [miezekatzendompteur/guiBee#3]
Hello, 
The guiBee software seems sometimes to record data as duplicates and the first Input lines (before any signals) would be not really needed. If implementing these changes would take much time, we can deal if it during the data analysis.
Thanks, 
Chris

**Comment by miezekatzendompteur** [comment]
The problem is solved in version 1.0.1.0

**Comment by chriskurze** [comment]
Hello , 
Somehow we had recently data recording issues. (1) When starting, the data is sometimes not recorded. Restarting the PC seem to help. (2) After 1h of recording, it suddenly stopped. Unfortunately, I did not realize it immediately. Restarting the programme did not help. 
Is there a way to solve the issue in our lab, as I am currently running experiments?
Thanks.
Christoph
